place=['maldives','seattle','newyork','egypt','shanghai']
print(place)
#使用方法sorted()排序
print(sorted(place))
#参看原始列表
print(place)
#使用方法sorted()反向排序
print(sorted(place,reverse=True))
#参看原始列表
print(place)
#使用方法reverse()反转列表中元素
place.reverse()
print(place)
#使用方法reverse()再次反转列表中元素，恢复原序列
place.reverse()
print(place)
#使用方法sort()排序
place.sort()
print(place)
#使用方法sort()反转排序
place.sort(reverse=True)
print(place)
